name: CI

on:

  push:
    branches: [ "dynamic" ]
  pull_request:
    branches: [ "dynamic" ]

  workflow_dispatch:
jobs:
  BuildKernel:
    runs-on: ubuntu-20.04
    environment: TOKEN
    env:
      TOKEN: ${{ secrets.TOKEN_ID }}     
    steps:
      - uses: actions/checkout@v3        
      - name: build kernel
        run: |
          git clone https://github.com/tiann/KernelSU
          sudo apt update
          sudo apt install android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
          sudo ln -sf python2.7 /usr/bin/python
          sudo -S TOKEN=$TOKEN ./tg.sh

      - name: upload kernel
        uses: actions/upload-artifact@master
        with:
            name: EXTRACKME
            path: Quartz*.zip
